server:
  port: 8081
jwt:
  secret: zSLkGjZCe1mJbkLlI77Mw9eP0wx7XZJC5TbIE6/F5we7brZ0Pp+Et9e0A4QXNWaA
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_2
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
